// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz476NAVJS6OIKgiBYs7zkZLwxJTLkvlk',
    appId: '1:645591083879:web:f1fddfdeef37b1bd1a1dc2',
    messagingSenderId: '645591083879',
    projectId: 'kodar-58d3a',
    authDomain: 'kodar-58d3a.firebaseapp.com',
    storageBucket: 'kodar-58d3a.appspot.com',
    measurementId: 'G-LRLHPN2Q6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZpxczgqCMtJthKM0zpEVSjS1b0vdJpw8',
    appId: '1:645591083879:android:09444231304dc0591a1dc2',
    messagingSenderId: '645591083879',
    projectId: 'kodar-58d3a',
    storageBucket: 'kodar-58d3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS_7J8-hJcNZlp4cvF2hvU43LKnszrPhI',
    appId: '1:645591083879:ios:77d1809b41503aaf1a1dc2',
    messagingSenderId: '645591083879',
    projectId: 'kodar-58d3a',
    storageBucket: 'kodar-58d3a.appspot.com',
    iosBundleId: 'com.example.webKsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS_7J8-hJcNZlp4cvF2hvU43LKnszrPhI',
    appId: '1:645591083879:ios:8c96045c2afe11d41a1dc2',
    messagingSenderId: '645591083879',
    projectId: 'kodar-58d3a',
    storageBucket: 'kodar-58d3a.appspot.com',
    iosBundleId: 'com.example.webKsa.RunnerTests',
  );
}
